### ISSUE TITLE
Speed up CI

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#391] opened 2021-02-23 05:03 UTC
# Problem

Currently CI takes close to 30m to run.

18m for deps and running tests 7m.

## Acceptance criteria

Run CI in <10m.

**Comment by oskarth** [comment] 2021-05-24 05:17
The biggest offender here by far is Windows CI, taking 50m or so for a full run. This is basically unusable.

Any ideas for how we can make this faster? Currently this is using GH actions.

cc @jakubgs @jm-clius

**Comment by jakubgs** [comment] 2021-05-25 08:18
@arthurk please check this out. Should be simple to fix with some caching.

If not we can move windows or all builds to Jenkins since caching there is pretty straightforward.

**Comment by arthurk** [comment] 2021-05-31 06:22
I've tried to optimize this but it's not a simple fix by enabling caching. The `COPY` command in the Dockerfile will always invalidate the cache when a file changes, leading to subsequent commands to be executed (git submodule, make deps, ...):

https://github.com/status-im/nim-waku/blob/8f741de483a0dd4ac180dc634191b1060ebd2737/Dockerfile#L12-L18

We also run an image prune after each CI job, which makes caching impossible:

https://github.com/status-im/nim-waku/blob/8f741de483a0dd4ac180dc634191b1060ebd2737/Jenkinsfile#L59

If we want to remove this, we'd need a cronjob periodically pruning the cache (like once a week) to avoid the disk getting full.

**Comment by jakubgs** [comment] 2021-05-31 08:30
I think Oskar is referring to GitHub actions CI they use. Jenkins CI is only used to deploy to the fleets.

**Comment by arthurk** [comment] 2021-05-31 08:37
Got it, I'll focus on speeding up the GH actions workflow

**Comment by oskarth** [comment] 2021-06-14 10:45
Any progress on this @arthurk?

**Comment by jakubgs** [comment] 2021-06-22 08:44
Looks like no progress has been made. I wall take it over.

**Comment by jakubgs** [comment] 2021-06-22 09:16
Looks like for both MacOS and Linux the biggest step is installing dependencies:

https://github.com/status-im/nim-waku/blob/82bad26e0287234fe55f6a5318209634d4350e12/.github/workflows/test.yml#L40-L43

![image](https://user-images.githubusercontent.com/2212681/122898539-421ae980-d34b-11eb-999a-7a4be358cc94.png)

**Comment by jakubgs** [comment] 2021-06-22 09:17
But on Windows the biggest part appears to be running the tests:

https://github.com/status-im/nim-waku/blob/82bad26e0287234fe55f6a5318209634d4350e12/.github/workflows/test.yml#L88-L92

![image](https://user-images.githubusercontent.com/2212681/122898719-64146c00-d34b-11eb-81dc-05257488625a.png)

**Comment by jakubgs** [comment] 2021-06-23 21:05
As far as I can tell in https://github.com/status-im/nim-waku/pull/644 the issue isn't building dependencies but the actual binaries:

![image](https://user-images.githubusercontent.com/2212681/123167858-6c69c580-d477-11eb-8621-36acff541c02.png)

I'm not sure what you can do about binaries being slow to build. That's just not something you can cache like dependencies.
Unless I guess we skip building some of the binaries that we just don't need.

We could do some fancy logic to kinda detect what actually changed and build just that, but not sure how easy that would be.

**Comment by oskarth** [comment] 2021-06-24 04:42
Why are running tests on Windows so slow? Is this about the instance? What does this look like locally? @jm-clius if you know. One option would be to use Jenkins here, either 100% for all PRs or for Windows builds on master/nightly (then disable for PRs).

**Comment by jm-clius** [comment] 2021-06-24 07:10
> What does this look like locally?

I've only used Ubuntu locally, but it may be time to set up a local build so we have a better grasp of different platforms.

**Comment by jakubgs** [comment] 2021-06-24 07:42
If I split it up further we can see that V1 stuff takes much less time than V2:

## Linux

![image](https://user-images.githubusercontent.com/2212681/123222561-5a684100-d4d0-11eb-9322-32598428d45a.png)

## Windows

![image](https://user-images.githubusercontent.com/2212681/123222644-6bb14d80-d4d0-11eb-86d5-53efa2ce193f.png)

**Comment by jakubgs** [comment] 2021-06-24 17:32
Looks decent on Linux and MacOS. Windows is slower, but then again our Windows host isn't that beefy.

### Linux

![image](https://user-images.githubusercontent.com/2212681/123307418-c1aee100-d522-11eb-9178-7213f8b92f7d.png)
https://ci.status.im/job/nim-waku/job/prs/job/linux/view/change-requests/job/PR-644/

### MacOS

![image](https://user-images.githubusercontent.com/2212681/123307498-d8edce80-d522-11eb-9143-93fb1f532abb.png)
https://ci.status.im/job/nim-waku/job/prs/job/macos/view/change-requests/job/PR-644/

### Windows

![image](https://user-images.githubusercontent.com/2212681/123305846-ddb18300-d520-11eb-95cb-449851ed6113.png)
https://ci.status.im/job/nim-waku/job/prs/job/windows/job/PR-644/

**Comment by jakubgs** [comment] 2021-06-24 17:35
I have been considering switching the Windows host from `n2-standard-4` to `n2d-highcpu-8`. But the issue with that is that the host has only 8 GB of memory, which I'm not sure would be enough for Desktop workloads. But it's worth a try.

Docs: https://cloud.google.com/compute/docs/machine-types

**Comment by jakubgs** [comment] 2021-06-28 19:34
I've marked the https://github.com/status-im/nim-waku/pull/644 PR ready for review after some cleanup.

The Windows builds are faster, but 36 minutes is still a bit slow. Once we merge this we can disable GitHub builds.

**Comment by jakubgs** [comment] 2021-06-29 17:55
I've merged #644, but there's some room for improvement by only running builds and tests for what has been changed.

**Comment by jakubgs** [comment] 2021-06-30 17:22
I've added `cleanWs()` call to clean up workspaces because they take up too much space: https://github.com/status-im/nim-waku/pull/655

**Comment by jakubgs** [comment] 2021-07-02 07:11
The #656 PR adds some basic regex checks of the diff to find which files changed to avoid running all builds/tests.

**Comment by oskarth** [comment] 2021-07-14 08:46
@jakubgs seems like https://github.com/status-im/nim-waku/pull/665 Windows CI takes about an hour still. That PR is only touching v2 stuff as well

**Comment by jakubgs** [comment] 2021-07-14 15:43
Yeah, and if you look at the build it's only building V2 stuff:

![image](https://user-images.githubusercontent.com/2212681/125651344-fe252cd7-d82d-4f1d-95c4-8f188c3bc275.png)

**Comment by oskarth** [comment] 2021-07-15 05:30
Right, the point is that we are basically at same (or worse) for Windows CI as we were before with GH actions :)

**Comment by jakubgs** [comment] 2021-07-15 06:42
Well, Windows is garbage, so that's to be expected =].

**Comment by jakubgs** [comment] 2021-07-15 06:43
We can try switching one of the hosts to `n2d-highcpu-8`, but my expectation is that it won't have enough RAM.

**Comment by jakubgs** [comment] 2021-07-15 06:46
For fuck's sake:
```
Error: Error waiting for starting instance: Quota 'N2D_CPUS' exceeded.  Limit: 0.0 in region europe-west4.
```

**Comment by jakubgs** [comment] 2021-07-15 06:50
Okay, then how about a `c2-standard-4` which is compute-optimized:
https://cloud.google.com/compute/docs/compute-optimized-machines

**Comment by jakubgs** [comment] 2021-07-15 06:56
Okay, I switched `windows-02.gc-europe-west4-a.ci.misc` to `c2-standard-4`:
```
NAME                                  ZONE            MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP    STATUS
windows-02-gc-europe-west4-a-ci-misc  europe-west4-a  c2-standard-4               10.164.0.19  34.91.249.159  RUNNING
```
Lets see what happens.

**Comment by jakubgs** [comment] 2021-07-15 07:42
I built `status-desktop` on `02` and it was twice as fast, so that's something.

**Comment by jakubgs** [comment] 2021-07-15 08:16
It's better, 32 minutes:
https://ci.status.im/job/nim-waku/job/prs/job/windows/view/change-requests/job/PR-667/2/

**Comment by jakubgs** [comment] 2021-07-15 08:18
I've made the change permanent: https://github.com/status-im/infra-ci/commit/bb1c8fbb

**Comment by jakubgs** [comment] 2021-07-15 13:25
Apparently Windows OpenSSH supports only `ed25519` keys: https://github.com/PowerShell/Win32-OpenSSH/issues/973

**Comment by jakubgs** [comment] 2021-08-03 06:58
I'm going to close this. If there's more work necessary specific to any build we can open a new issue.

**Closed by jakubgs** 2021-08-03 06:58 UTC
